[tool.poetry]
name = "d2-ogre-kick"
version = "0.1.0"
description = "Destiny 2 - 棱镜虚空猎自动踢战争领主的废墟首Boss（Ogre踢）"
authors = ["溜溜球99九九 (视频) / WorkBuddy (脚本)"]
readme = "README.md"
packages = [{include = "d2_ruin_farm"}]

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
loguru = "^0.7.2"
pydirectinput = "^1.0.4"
opencv-python = "^4.9.0.80"
pillow = "^10.3.0"
pyinstaller = "^6.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
